"""rename department.

Revision ID: 11eda658f7f5
Revises: b2f7ab8a15f9
Create Date: 2024-08-26 20:12:45.737161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11eda658f7f5'
down_revision = 'b2f7ab8a15f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
    # ### end Alembic commands ###
