"""add Department

Revision ID: 409cbde28759
Revises: 81c08404d685
Create Date: 2024-07-15 15:24:34.926203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409cbde28759'
down_revision = '81c08404d685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
